# Require the standard build environment
sudo: required

# Require Ubuntu 14.04
dist: trusty

# Require Docker
services:
  - docker

before_cache:
  - rm --force --recursive --verbose $HOME/.m2/repository/com/github/gantsign

cache:
  directories:
    - $HOME/.m2

script: .travis/build.sh

branches:
  only:
    - master
    - /^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)([\.\-].*)?$/

env:
  global:
    - secure: KkK/+CebKZbNKqidfgzgtNUyHxr/GtokCpeayX82SUNloEg76nxh/89rEDSlPIBbLN5Re078R/HITL9OekuZWOl06sSRP+3wsG37QC68wB7bJE4T9/32sl84GwUfmDq8amZU5ig+RQMZSsHPgTB5oS02im0SKpoNgnqNAUpRltTQYgz0FAg0P0L1KL9KdhO/aHeIU3fFq+schZdPRBd3i/CERCLeGl1yz3dy0GeKkXmkfcV1G549g3HGGJoB8D6K5G/3lxSjjfHF9+YOXBxJc6J5DRbwqkFCbF7ZduV8rwIKWra79UJRJjn6WLZ3MyIeG0BF/0DYzspr/6HlxE1nEl/zujSx8TlRg+ECXhwg9EI6rvGg5AbB+ks3IqeK/znJ07i5wi1P3Su5AccNbDjYXa/zhrTsYTzhTvYlJQgAxZP/lEikX+lDBC6P/MgoSFXCkYRafKRSF8RtdLn7BP6NI7OPE5yHToH+xrCZLsHrwXLZSz3vaikUTY6517fQUBTiUV8B/HtxeZdqgbyN4xho4C03mhfKqdgBWGxryT0AL1kTFROtsyY6UGFm0wnQa9LGefc8H+j/hbnRRFh8Zi2oAS4oi+3gFNeR+zwIKynZBxze9sYA77wuxj1S23fzJKVyxNlrEBdJUlasWujgRITZOwANJCxwCIxLJ8i5W0FakZg=
    - secure: aU/9/dOGqnuJCsxjHChoYnyZeqaVT7C/fOMT8FUDZuzVb1co/C7+dhPbB8dQNn9I/PAtZ5Bk0nHCvWLCsYGVvzwZ/D12HWWjms4ucPBlPOylddaAwOl1WPFoi2TQ6Gi6bzmspG/9DGYw0tLa3joy2MxxdK07+YyI094JCQrNTrJq6kUHdQjdSIEkn6HUZFl1b1srlJdLQYMNEMzU/TSRDpiVi5QxJp90gWRwy0MvGy1/nX91hO4oJK2gFI6r63Lo77hRJ4k6GOQnjB66XXHhx6TO4oMWsZCILBoI0bqDIBQ1ywl7seQmXO55kJKaKOQJUHvT1BxBNVpg6lyvB4nIEPa0AKMkYZXZvRr1sorpP2p7MHHeeUyWCt6UWxAzYnXa6dHBO6fHfsTza4vb309dPxn+E8cb1gjtU3Xwk+xKHNUdVOTET9ByH15AN5+FS9e1ttbPyz4pL77JuM9usEe78M6QFqTYFkKyP3UZ+axHpCestpUoE6dworeioLaUfJXXMZ92QqZpAcyRMzdn4CWRY7xYwNKKytJAXSiMFMoQ1BxGZ+KcKI5Hfr0LzCNlg7zdSmDVselHy1ceHC4BrDfJur9y3nB034m+qAI+PYf/eyTOUFaAShVpOYCQz+Ap6kFmn9wZHZcuNXPjDK8viryT7OBIWtbDFeDBIPkBeQlEYJs=
    - secure: odO6AyhPBZSCFlY90vPFxdFBwST0ZsuvsJa5CZc6D/ec71euQkJmZi5rlCcZJColrr8pFCyq5MiLbYze6Mrlh34nbq9z2CT+dppijJMe3kBvcNX2t3+T/uM89TiR+zooFRiD+zrVgFB3rxm9JhA3IvflAXciO+X1v9bvm6e1e7mOUIMitrQqxPe9YYuK/UNj7wTNDw7LyJMeD311MauN9F0BdKT1DNYFhNTF3aT71wV8S4wi84htVrRosmfbjS+mjiYCQQ1oZz1O2zj5mPmJkhe6iyDbUABhqGJe1aIFWCLxDpUfHiWMUICv6DqBSwf+LNMIocUFrhk8AUa4mky0o/lCKfj8Smqp2wveH7zw3jOfXCGYGdov/EpDnaLG+lk/KGz8b46ceFLucfSjHw3ND4YCHyrUmI6I7xJPxCVjx3kufarshoR0GeJZDAVXcgBe89iyRj08pE3z93wMritK2DfymtFBI4vZP5y5+ZnPaZjEpsXI9mHwSw2i0oewppxyiqCAYZvS3D1h4DNmLuBrlw1d8sN4N1O0yvbTAROxwCq+FYwUp2vS93SKZ69ucR1Tl0AHcE9a57MsdUV7G6qLtqeA6GbS1VfC+IGtyu9bZU763X/ZPb+9N/WX9wT+0HihfHgfQr4kH7RxjtG+MmF+YJDt1mS6dQWg4JjdWK0MObQ=
    # VersionEye API KEY
    - secure: q/mfZo5aZOUco57DgKgBytJnqfd2eY9bcpGlCX6aE8uzlXc6enXw6EfCqnO1XSU6wsLY6imA+TqtdbmRZZyG17jwPe2IfVWlIkBvubeDSi+FmoEcc+Ru458S33VAaPQ4QNZgxQ02ZaFNuepC5ZeMhaA2phWeRsL/lWsGjO+GJv+EwCKUH4q6dh9tTSd2A6FefTtkH8yxmmT90TFNLeXN/O58Ee6/5pMbgZmFd9V7Oi8SqPxPMm4XFHgRNn63oK4p106fq83JCIpSoKHFRvwIFBnSjzM92w+leOHaPKns1ckUiiwllojVGP8FukPH4EzixTT7zRXiYEV7sf65IF++02121rjN5h3HURUkyhtvp0ceg7FICMCH1k6oAKdBdQVnTBykSsbBBmAS4KdPEZkLFan3rmws/HxQLK2/WyOGM0IDf0kNW+eTRQbpTsINGVmuP4L56FTt5DnVpYSSmK4LIFpFQ3pNUSdOJnIHR7z3qVPtAGkZbyL//a6BnXlP4BD0begrN9BeTcz6NbZZXttuwsJiI98GUVVw+RzlLN7/EDP/jhAk2U+UCG4ed99De+oWsdfKtSriPBK7WD8Uzv9MYw/h2P7FLREjMAQ0PNMuZpXd3nkfZZ8uGAt/HeKRRKVobrxax/N6ufZCXI3N0Ec+y60oKKlHfvkZ0gD43gKD6mk=
