# Require the standard build environment
sudo: required

# Require Ubuntu 14.04
dist: trusty

# Require Docker
services:
  - docker

before_cache:
  - rm --force --recursive --verbose $HOME/.m2/repository/com/github/gantsign

cache:
  directories:
    - $HOME/.m2

script: .travis/build.sh

branches:
  only:
    - master
    - /^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)([\.\-].*)?$/
