# Require the standard build environment
sudo: required

# Require Ubuntu 14.04
dist: trusty

# Require Docker
services:
  - docker

before_cache:
  - rm --force --recursive --verbose $HOME/.m2/repository/com/github/gantsign

cache:
  directories:
    - $HOME/.m2

script: .travis/build.sh

branches:
  only:
    - master
    - /^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)([\.\-].*)?$/

env:
  global:
    - secure: KkK/+CebKZbNKqidfgzgtNUyHxr/GtokCpeayX82SUNloEg76nxh/89rEDSlPIBbLN5Re078R/HITL9OekuZWOl06sSRP+3wsG37QC68wB7bJE4T9/32sl84GwUfmDq8amZU5ig+RQMZSsHPgTB5oS02im0SKpoNgnqNAUpRltTQYgz0FAg0P0L1KL9KdhO/aHeIU3fFq+schZdPRBd3i/CERCLeGl1yz3dy0GeKkXmkfcV1G549g3HGGJoB8D6K5G/3lxSjjfHF9+YOXBxJc6J5DRbwqkFCbF7ZduV8rwIKWra79UJRJjn6WLZ3MyIeG0BF/0DYzspr/6HlxE1nEl/zujSx8TlRg+ECXhwg9EI6rvGg5AbB+ks3IqeK/znJ07i5wi1P3Su5AccNbDjYXa/zhrTsYTzhTvYlJQgAxZP/lEikX+lDBC6P/MgoSFXCkYRafKRSF8RtdLn7BP6NI7OPE5yHToH+xrCZLsHrwXLZSz3vaikUTY6517fQUBTiUV8B/HtxeZdqgbyN4xho4C03mhfKqdgBWGxryT0AL1kTFROtsyY6UGFm0wnQa9LGefc8H+j/hbnRRFh8Zi2oAS4oi+3gFNeR+zwIKynZBxze9sYA77wuxj1S23fzJKVyxNlrEBdJUlasWujgRITZOwANJCxwCIxLJ8i5W0FakZg=
    - secure: aU/9/dOGqnuJCsxjHChoYnyZeqaVT7C/fOMT8FUDZuzVb1co/C7+dhPbB8dQNn9I/PAtZ5Bk0nHCvWLCsYGVvzwZ/D12HWWjms4ucPBlPOylddaAwOl1WPFoi2TQ6Gi6bzmspG/9DGYw0tLa3joy2MxxdK07+YyI094JCQrNTrJq6kUHdQjdSIEkn6HUZFl1b1srlJdLQYMNEMzU/TSRDpiVi5QxJp90gWRwy0MvGy1/nX91hO4oJK2gFI6r63Lo77hRJ4k6GOQnjB66XXHhx6TO4oMWsZCILBoI0bqDIBQ1ywl7seQmXO55kJKaKOQJUHvT1BxBNVpg6lyvB4nIEPa0AKMkYZXZvRr1sorpP2p7MHHeeUyWCt6UWxAzYnXa6dHBO6fHfsTza4vb309dPxn+E8cb1gjtU3Xwk+xKHNUdVOTET9ByH15AN5+FS9e1ttbPyz4pL77JuM9usEe78M6QFqTYFkKyP3UZ+axHpCestpUoE6dworeioLaUfJXXMZ92QqZpAcyRMzdn4CWRY7xYwNKKytJAXSiMFMoQ1BxGZ+KcKI5Hfr0LzCNlg7zdSmDVselHy1ceHC4BrDfJur9y3nB034m+qAI+PYf/eyTOUFaAShVpOYCQz+Ap6kFmn9wZHZcuNXPjDK8viryT7OBIWtbDFeDBIPkBeQlEYJs=
    # GitHub Token
    - secure: TNUDFy/Gp2g4xAypmS92JB+dxW/b51LcK8nkHxMgtI7Yg/Oy1J1OE0TxeCO3pt/npsZnIKpMdFoklVuY42682st2vXYr35BK7upytWPkDQnSunInEwMIW9b67xsla9Ok/3KZzgByY9lqF5ZcV775/NyG+jkxai13A/I49yb6hQdnRF4axXFDeghrtlBBUwn6ssEbeXnA+YKmkgAFb7bNIGUFC76OdWFGQJNLfLX8eeUey5tb9wGB4RsWZhyqBg866wfro7xl8uzEKJ/9HPfV8NoS2vO/gSlQKtkyz3Hm+ZLool3g0kgJ/bLEoGulv+SKK//3RVl19jmUammdtF6aQ5t0DFca04Y7hhsCeO19qLjkK2bqiNYTEC5S48WM2FuMpp9hE2d0Ti01iCy8jhtclAkhoxIegH1QNheBXC3Sjmb4E2evGPkWq2LIPaYUxV/j+8NOHb2YbEvtnPmj8hnwzhEIsKImtQXBPfwQ+E2/zQI8/r1CBu4I9vh2MbjnE157ea4C87ZRNZwSFI+px1/WUuwKqbPgGVCzaOZmEvfT27hH1xD6zdGhG/ddkBt0EQrflSVLB223q1VEqhVqAycKxsp6x5YO3FRfbxFWo0nYIDqvErEAy7i6u0HRJTXJrgqwppBbr9UudOXrkGMGmMqntW2T5BTaFvG014OW14csB2I=
