language: java
jdk:
  - oraclejdk8

script: mvn install

after_success:
  - test "${TRAVIS_PULL_REQUEST}" == "false" && test "${TRAVIS_TAG}" != "" && mvn deploy --settings .travis/settings.xml -P publish-artifacts

env:
  global:
    - secure: KkK/+CebKZbNKqidfgzgtNUyHxr/GtokCpeayX82SUNloEg76nxh/89rEDSlPIBbLN5Re078R/HITL9OekuZWOl06sSRP+3wsG37QC68wB7bJE4T9/32sl84GwUfmDq8amZU5ig+RQMZSsHPgTB5oS02im0SKpoNgnqNAUpRltTQYgz0FAg0P0L1KL9KdhO/aHeIU3fFq+schZdPRBd3i/CERCLeGl1yz3dy0GeKkXmkfcV1G549g3HGGJoB8D6K5G/3lxSjjfHF9+YOXBxJc6J5DRbwqkFCbF7ZduV8rwIKWra79UJRJjn6WLZ3MyIeG0BF/0DYzspr/6HlxE1nEl/zujSx8TlRg+ECXhwg9EI6rvGg5AbB+ks3IqeK/znJ07i5wi1P3Su5AccNbDjYXa/zhrTsYTzhTvYlJQgAxZP/lEikX+lDBC6P/MgoSFXCkYRafKRSF8RtdLn7BP6NI7OPE5yHToH+xrCZLsHrwXLZSz3vaikUTY6517fQUBTiUV8B/HtxeZdqgbyN4xho4C03mhfKqdgBWGxryT0AL1kTFROtsyY6UGFm0wnQa9LGefc8H+j/hbnRRFh8Zi2oAS4oi+3gFNeR+zwIKynZBxze9sYA77wuxj1S23fzJKVyxNlrEBdJUlasWujgRITZOwANJCxwCIxLJ8i5W0FakZg=
    - secure: aU/9/dOGqnuJCsxjHChoYnyZeqaVT7C/fOMT8FUDZuzVb1co/C7+dhPbB8dQNn9I/PAtZ5Bk0nHCvWLCsYGVvzwZ/D12HWWjms4ucPBlPOylddaAwOl1WPFoi2TQ6Gi6bzmspG/9DGYw0tLa3joy2MxxdK07+YyI094JCQrNTrJq6kUHdQjdSIEkn6HUZFl1b1srlJdLQYMNEMzU/TSRDpiVi5QxJp90gWRwy0MvGy1/nX91hO4oJK2gFI6r63Lo77hRJ4k6GOQnjB66XXHhx6TO4oMWsZCILBoI0bqDIBQ1ywl7seQmXO55kJKaKOQJUHvT1BxBNVpg6lyvB4nIEPa0AKMkYZXZvRr1sorpP2p7MHHeeUyWCt6UWxAzYnXa6dHBO6fHfsTza4vb309dPxn+E8cb1gjtU3Xwk+xKHNUdVOTET9ByH15AN5+FS9e1ttbPyz4pL77JuM9usEe78M6QFqTYFkKyP3UZ+axHpCestpUoE6dworeioLaUfJXXMZ92QqZpAcyRMzdn4CWRY7xYwNKKytJAXSiMFMoQ1BxGZ+KcKI5Hfr0LzCNlg7zdSmDVselHy1ceHC4BrDfJur9y3nB034m+qAI+PYf/eyTOUFaAShVpOYCQz+Ap6kFmn9wZHZcuNXPjDK8viryT7OBIWtbDFeDBIPkBeQlEYJs=
