name: Release
on:
  push:
    tags:
      - '*'
env:
  JAVA_TOOL_OPTIONS: >-
    -XX:TieredStopAtLevel=1
    -XX:+UseParallelGC
    -Dstyle.color=always
    -Djansi.force=true

jobs:
  build:
    name: Maven build
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Build with Maven
        run: |-
          export GIT_TAG="${GITHUB_REF#refs/tags/}"
          .github/scripts/build.sh

  build-all:
    if: ${{ always() }}
    name: Build (matrix)
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - name: Check build matrix status
        run: "[[ '${{ needs.build.result }}' == 'success' ]] || exit 1"

  deploy:
    name: Maven deploy
    runs-on: ubuntu-18.04
    needs: build-all
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Install GPG key
        run: |-
          gpg --batch --import-options import-show --import << EOF
          ${{ secrets.GPG_KEY }}
          EOF
      - name: Deploy with Maven
        run: |-
          export GIT_TAG="${GITHUB_REF#refs/tags/}"
          .github/scripts/deploy.sh
        env:
          OSSRH_USER: ${{ secrets.OSSRH_USER }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          GPG_KEY_NAME: ${{ secrets.GPG_KEY_NAME }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - name: Delete GPG secret key
        if: ${{ always() }}
        run: gpg --batch --yes --delete-secret-keys ${{ secrets.GPG_KEY_NAME }} || true
      - name: Delete GPG public key
        if: ${{ always() }}
        run: gpg --batch --yes --delete-keys ${{ secrets.GPG_KEY_NAME }}

  deploy-site:
    name: Maven deploy site
    runs-on: ubuntu-18.04
    needs: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Configure Git user
        run: >-
          git config user.name 'John Freeman' &&
          git config user.name '17984707+freemanjp@users.noreply.github.com'
      - name: Deploy Maven site
        run: |-
          export GIT_TAG="${GITHUB_REF#refs/tags/}"
          .github/scripts/deploy-site.sh
        env:
          GITHUB_USER: ${{ secrets.GITHUB_USER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
